export const GET_USERS = 'HOME_GET_USERS';
export const GET_USERS_SUCCESS = 'HOME_GET_USERS_SUCCESS';
export const GET_USER_DETAILS = 'HOME_GET_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS = 'HOME_GET_USER_DETAILS_SUCCESS';
export const ERROR = 'ERROR';
